
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dashboard-monitoring-back
  name: dashboard-monitoring-back
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: dashboard-monitoring-back
